/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        // Базовые цветовые палитры
        purple: {
          50: "#f5f1f9",
          100: "#e0d2ec",
          200: "#cab4e0",
          300: "#b596d3",
          400: "#a078c7",
          500: "#8755b8",
          600: "#7545a4",
          700: "#5f3886",
          800: "#4a2b68",
          900: "#341f49",
          950: "#1f122b",
          DEFAULT: "#61378A",
        },
        orange: {
          50: "#fef1ec",
          100: "#fad4c4",
          200: "#f7b69d",
          300: "#f49975",
          400: "#f17c4d",
          500: "#ed5417",
          600: "#d84911",
          700: "#b03c0e",
          800: "#882e0b",
          900: "#612107",
          950: "#391304",
          DEFAULT: "#ED5417",
        },
        neutral: {
          50: "#f5f4f6",
          100: "#dfdde2",
          200: "#cac6ce",
          300: "#b5afba",
          400: "#9f97a7",
          500: "#877d90",
          600: "#746b7e",
          700: "#5f5766",
          800: "#49444f",
          900: "#343038",
          950: "#1f1c21",
          black: "#000",
          white: "#fff",
        },
        red: {
          50: "#fdecec",
          100: "#fac5c5",
          200: "#f69e9e",
          300: "#f27777",
          400: "#ef4f4f",
          500: "#eb2626",
          600: "#d51414",
          700: "#ae1010",
          800: "#860c0c",
          900: "#5f0909",
          950: "#380505",
        },

        // Семантические цвета через CSS-переменные
        surface: {
          primary: "var(--neutral-50)",
          secondary: "var(--neutral-white)",
          "secondary-hover": "var(--neutral-200)",
          "secondary-pressed": "var(--neutral-300)",
          brand: "var(--purple-800)",
          "brand-overlay": "var(--purple-900)",
          complimentary: "var(--orange-400)",
          muted: "var(--neutral-100)",
          disabled: "var(--neutral-100)",
          indicator: {
            DEFAULT: "var(--neutral-300)",
            hover: "var(--neutral-400)",
          },
        },
        text: {
          primary: "var(--neutral-900)",
          secondary: "var(--neutral-700)",
          tertiary: "var(--neutral-500)",
          interactive: "var(--purple-600)",
          "interactive-hover": "var(--purple-700)",
          "interactive-pressed": "var(--purple-700)",
          "interactive-visited": "#8361A4",
          "on-interactive": "var(--neutral-white)",
          "accent-alt": "var(--orange-500)",
          "accent-brand": "var(--purple-500)",
          negative: "var(--red-600)",
          disabled: "var(--neutral-400)",
          "on-brand": "var(--neutral-white)",
          "on-brand-secondary": "var(--purple-200)",
          "on-complimentary": "var(--neutral-white)",
        },
        border: {
          DEFAULT: "var(--neutral-200)",
          subtle: "var(--neutral-100)",
          "default-hover": "var(--neutral-300)",
          interactive: "var(--purple-600)",
          focused: "var(--purple-600)",
          negative: "var(--red-500)",
          divider: "var(--neutral-200)",
          "sublte-on-brand": "var(--purple-700)",
        },
        interactive: {
          background: {
            primary: "var(--purple-500)",
            "primary-hover": "var(--purple-600)",
            "primary-pressed": "var(--purple-700)",
            "secondary-hover": "var(--purple-100)",
            "secondary-pressed": "var(--purple-200)",
            complimentary: "var(--orange-500)",
            "complimentary-hover": "var(--orange-600)",
            "complimentary-pressed": "var(--orange-700)",
          },
          overlay: {
            "on-brand-hover": "rgba(255,255,255,0.1)",
            "on-brand-pressed": "rgba(255,255,255,0.2)",
            DEFAULT: "rgba(74,44,104,0.1)",
            "default-hover": "rgba(74,44,104,0.2)",
          },
        },
        link: {
          "on-brand": "var(--neutral-white)",
        },

        // Ваши кастомные цвета (для обратной совместимости)
        bg: "#fafafa",
        pureWhite: "#F5F5F5",
        white2: "#F9F9F9",
        white3: "#F2F9FF",
        black1: "#0C0C0D",
        black2: "#1A1A1A",
        gray: "#8D9399",
        gray3: "#8E9499",
        lightRed: "#F06C74",
      },
      dropShadow: {
        cardShadow: "0 4px 20px rgba(0, 0, 0, 0.25)",
        headerShadow: "0 1px 2px rgba(0, 0, 0, 0.10)",
        participantsCardShadow: "0 2px 8px rgba(0, 0, 0, 0.16)",
        rectCardShadow: "0 2px 4px rgba(0, 0, 0, 0.10)",
      },
      backgroundImage: {
        HOME_PATTERN: "url('/images/home-bg.png')",
        HEADER_PATTERN: "url('/images/header-bg.png')",
        FOOTER_PATTERN: "url('/images/footer-bg.png')",
        AUTH_BTN_PATTERN: "url('/images/auth-btn-bg.png')",
        POEM_PATTERN: "url('/images/poems/1.png')",
      },
      screens: {
        mob: "440px",
        tab: "980px",
        px850: "850px",
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [
    function ({ addBase, theme }) {
      addBase({
        ":root": {
          // Neutral цвета
          "--neutral-50": theme("colors.neutral.50"),
          "--neutral-100": theme("colors.neutral.100"),
          "--neutral-200": theme("colors.neutral.200"),
          "--neutral-300": theme("colors.neutral.300"),
          "--neutral-400": theme("colors.neutral.400"),
          "--neutral-500": theme("colors.neutral.500"),
          "--neutral-600": theme("colors.neutral.600"),
          "--neutral-700": theme("colors.neutral.700"),
          "--neutral-800": theme("colors.neutral.800"),
          "--neutral-900": theme("colors.neutral.900"),
          "--neutral-950": theme("colors.neutral.950"),
          "--neutral-white": theme("colors.neutral.white"),
          "--neutral-black": theme("colors.neutral.black"),

          // Purple цвета
          "--purple-50": theme("colors.purple.50"),
          "--purple-100": theme("colors.purple.100"),
          "--purple-200": theme("colors.purple.200"),
          "--purple-300": theme("colors.purple.300"),
          "--purple-400": theme("colors.purple.400"),
          "--purple-500": theme("colors.purple.500"),
          "--purple-600": theme("colors.purple.600"),
          "--purple-700": theme("colors.purple.700"),
          "--purple-800": theme("colors.purple.800"),
          "--purple-900": theme("colors.purple.900"),
          "--purple-950": theme("colors.purple.950"),

          // Orange цвета
          "--orange-50": theme("colors.orange.50"),
          "--orange-100": theme("colors.orange.100"),
          "--orange-200": theme("colors.orange.200"),
          "--orange-300": theme("colors.orange.300"),
          "--orange-400": theme("colors.orange.400"),
          "--orange-500": theme("colors.orange.500"),
          "--orange-600": theme("colors.orange.600"),
          "--orange-700": theme("colors.orange.700"),
          "--orange-800": theme("colors.orange.800"),
          "--orange-900": theme("colors.orange.900"),
          "--orange-950": theme("colors.orange.950"),

          // Red цвета
          "--red-50": theme("colors.red.50"),
          "--red-100": theme("colors.red.100"),
          "--red-200": theme("colors.red.200"),
          "--red-300": theme("colors.red.300"),
          "--red-400": theme("colors.red.400"),
          "--red-500": theme("colors.red.500"),
          "--red-600": theme("colors.red.600"),
          "--red-700": theme("colors.red.700"),
          "--red-800": theme("colors.red.800"),
          "--red-900": theme("colors.red.900"),
          "--red-950": theme("colors.red.950"),
        },
      });
    },
    require("tailwindcss-animate"),
  ],
};
