export const themeData = [
  {
    title: 'Товары для новорожденных и малышей',
    titleEn: 'Goods for newborns and babies',
    path: '/assets/icons/theme/baby.svg',
    link: '',
  },
  {
    title: 'Товары для школы (канцелярские принадлежности, детская мебель)',
    titleEn: "Goods for school (stationery, children's furniture)",
    path: '/assets/icons/theme/bag.svg',
    link: '',
  },
  {
    title: 'Образование и обучение для детей',
    titleEn: 'Education and training for children',
    path: '/assets/icons/theme/sciense.svg',
    link: '',
  },
  {
    title: 'Игрушки и развивающие пособия',
    titleEn: 'Toys and developmental aids',
    path: '/assets/icons/theme/toys.svg',
    link: '',
  },
  {
    title: 'Танцы, музыка и искусство в детской жизни',
    titleEn: "Dance, music and art in children's life",
    path: '/assets/icons/theme/dance.svg',
    link: '',
  },
  {
    title: 'Здоровье и безопасность детей',
    titleEn: 'Health and safety for children',
    path: '/assets/icons/theme/health.svg',
    link: '',
  },
  {
    title: 'Инновационные технологии в детском образовании',
    titleEn: "Innovative technologies in children's education",
    path: '/assets/icons/theme/technology.svg',
    link: '',
  },
  {
    title: 'Детская литература и чтение',
    titleEn: "Children's literature and reading",
    path: '/assets/icons/theme/reading.svg',
    link: '',
  },
  {
    title: 'Спорт и физическое развитие',
    titleEn: 'Sports and physical development',
    path: '/assets/icons/theme/sport.svg',
    link: '',
  },
  {
    title: 'Творчество и художественная деятельность',
    titleEn: 'Creativity and artistic activities',
    path: '/assets/icons/theme/paint.svg',
    link: '',
  },
  {
    title: 'Экологическое воспитание и устойчивость',
    titleEn: 'Environmental education and sustainability',
    path: '/assets/icons/theme/eco.svg',
    link: '',
  },
  {
    title: 'Детская мода и стиль',
    titleEn: "Children's fashion and style",
    path: '/assets/icons/theme/moda.svg',
    link: '',
  },
  {
    title:
      'Развлечения и мероприятия для детей (все для праздника) искусство и музыкальное образование',
    titleEn: 'Arts and music education',
    path: '/assets/icons/theme/exhibitions.svg',
    link: '',
  },
  {
    title: 'Инклюзивное образование и забота о детях с особенностями развития',
    titleEn: 'Inclusive education and care for children with special developmental needs',
    path: '/assets/icons/theme/incluzive.svg',
    link: '',
  },
  {
    title: 'Cемейные ценности и воспитание',
    titleEn: 'Family values and education',
    path: '/assets/icons/theme/cennost.svg',
    link: '',
  },
  {
    title: 'Технологии безопасности для детей',
    titleEn: 'Safety technologies for children',
    path: '/assets/icons/theme/inet-bez.svg',
    link: '',
  },
  {
    title: 'Питание и здоровое питание для детей',
    titleEn: 'Nutrition and healthy eating for children',
    path: '/assets/icons/theme/pitaniye.svg',
    link: '',
  },
  {
    title: 'Семейные развлечения и путешествия с детьми',
    titleEn: 'Family entertainment and traveling with children',
    path: '/assets/icons/theme/family.svg',
    link: '',
  },
  {
    title: 'Детская психология и развитие',
    titleEn: 'Child psychology and development',
    path: '/assets/icons/theme/head.svg',
    link: '',
  },
  {
    title: 'Технологии безопасного использования интернета для детей',
    titleEn: 'Internet safety technologies for children',
    path: '/assets/icons/theme/internet.svg',
    link: '',
  },
  {
    title: 'Роль родителей в развитии детей',
    titleEn: "The role of parents in children's development",
    path: '/assets/icons/theme/parents.svg',
    link: '',
  },
  {
    title: 'Детский туризм и путешествия',
    titleEn: "Children's tourism and traveling",
    path: '/assets/icons/theme/tourizm.svg',
    link: '',
  },
  {
    title: 'Интерактивные зоны для детей на открытом воздухе',
    titleEn: 'Outdoor interactive areas for children',
    path: '/assets/icons/theme/zone.svg',
    link: '',
  },
  {
    title: 'Креативные занятия и мастер-классы для детей',
    titleEn: 'Creative activities and master classes for children',
    path: '/assets/icons/theme/master-class.svg',
    link: '',
  },
];
